version: '3.2'


networks:
  hdpn:


services:
  namenode:
    command: namenode
    environment:
      CORE_SITE__FS_DEFAULTFS: "hdfs://namenode:9000"
      HDFS_SITE__DFS_REPLICATION: "1"
    hostname: namenode
    image: andahme/hadoop
    networks:
      - hdpn
    ports:
      - 9000:9000
      - 50070:50070
    volumes:
      - namenode-data:/tmp/hadoop-root/dfs/name

  datanode:
    command: datanode
    environment:
      CORE_SITE__FS_DEFAULTFS: "hdfs://namenode:9000"
    hostname: datanode
    image: andahme/hadoop
    networks:
      - hdpn
    ports:
      - 50010:50010
      - 50020:50020
      - 50075:50075
    volumes:
      - datanode-data:/tmp/hadoop-root/dfs/data

  resourcemanager:
    command: resourcemanager
    environment:
      MAPRED_SITE__MAPREDUCE_FRAMEWORK_NAME: "yarn"
    hostname: resourcemanager
    image: andahme/hadoop
    networks:
      - hdpn
    ports:
      - 8030-8033:8030-8033
      - 8088:8088

  nodemanager:
    command: nodemanager
    environment:
      YARN_SITE__YARN_RESOURCEMANAGER_HOSTNAME: "resourcemanager"
    hostname: nodemanager
    image: andahme/hadoop
    networks:
      - hdpn
    ports:
      - 8042:8042


volumes:
  namenode-data:
  datanode-data:

