version: '3.2'


networks:
  hdpn:


services:
  NameNode:
    command: namenode
    environment:
      CORE_SITE__FS_DEFAULTFS: "hdfs://namenode:9000"
      HDFS_SITE__DFS_REPLICATION: "1"
    hostname: namenode
    image: andahme/hadoop
    networks:
      hdpn:
        aliases:
          - namenode
    ports:
      - 9000:9000
      - 50070:50070
    volumes:
      - NameNode-data:/tmp/hadoop-root/dfs/name

  DataNode:
    command: datanode
    environment:
      CORE_SITE__FS_DEFAULTFS: "hdfs://namenode:9000"
    image: andahme/hadoop
    networks:
      - hdpn
    ports:
      - 50010:50010
      - 50020:50020
      - 50075:50075
    volumes:
      - DataNode-data:/tmp/hadoop-root/dfs/data

  ResourceManager:
    command: resourcemanager
    environment:
      MAPRED_SITE__MAPREDUCE_FRAMEWORK_NAME: "yarn"
    hostname: resourcemanager
    image: andahme/hadoop
    networks:
      hdpn:
        aliases:
          - resourcemanager
    ports:
      - 8030-8033:8030-8033
      - 8088:8088

  NodeManager:
    command: nodemanager
    environment:
      YARN_SITE__YARN_RESOURCEMANAGER_HOSTNAME: "resourcemanager"
    image: andahme/hadoop
    networks:
      - hdpn
    ports:
      - 8042:8042


volumes:
  NameNode-data:
  DataNode-data:

